### ISSUE TITLE
Scripting API — add function to set edit mode

### ISSUE THREAD

**Issue by cheeseonamonkey** [pierrehebert/LightningLauncher#3]
I recently had to jump through some hoops to achieve this, but I think it could be implemented easily in the native app:

- On the Android side with a simple intent launch by the app.
- On the JS scripting side, it would be best as a simple function in the main `LL`/`Lightning` API class, or perhaps in `Container` objects *(which have editable layouts).*

Seems like a good first issue - I intend to do this myself ASAP.

**Comment by TrianguloY** [comment]
You mean entering edit mode? (Like when you long press, and click the pencil button?)

If so, there is an action called "Edit Layout" that you can use. If you want it from a script, use `getActiveScreen().runAction(EventHandler.EDIT_LAYOUT, c); ` (c is the container you want to edit)

**Comment by cheeseonamonkey** [comment]
> You mean entering edit mode? (Like when you long press, and click the pencil button?)
> 
> If so, there is an action called "Edit Layout" that you can use. If you want it from a script, use `getActiveScreen().runAction(EventHandler.EDIT_LAYOUT, c); ` (c is the container you want to edit)

You are right actually, this is already a feature :)
