### ISSUE TITLE
Convert to Kotlin?

### ISSUE THREAD

**Issue by cheeseonamonkey** [pierrehebert/LightningLauncher#6]
### This would all be much for palatable to work with if it were using modern Kotlin, instead of all this dated Java :(

Is there a reliable way to cleanly automate such a conversion?

---

Most annoyingly:

>Before the introduction of enum classes in Java 5, developers used final constant ints to represent a fixed set of values. For example:
>```java
>public class Colors {
>    public static final int RED = 0;
>    public static final int GREEN = 1;
>    public static final int BLUE = 2;
>}
>```
>_(and all of the implications that might go along with this)_

**Comment by Aashishkebab** [comment]
> This would all be much for palatable to work with if it were using modern Kotlin, instead of this dated Java.
> 
> Most annoyingly:
> 
> > Before the introduction of enum classes in Java 5, developers used final constant ints to represent a fixed set of values. For example:
> > ```java
> > public class Colors {
> >    public static final int RED = 0;
> >    public static final int GREEN = 1;
> >    public static final int BLUE = 2;
> > }
> > ```

Yeah because Kotlin never gets updated, only Java changes and gets new features added to it.

If you would like, you can create a fork of this project for Kotlin, but I don't see any real advantage.

Converting this entire project into a different language is a big ask that won't serve any benefit unless Android suddenly stops supporting Java. If you would like to refactor the entire project into Kotlin, and then can prove it works just as before, feel free. There's even a tool built into Android Studio to facilitate this.

**Comment by cheeseonamonkey** [comment]
>Yeah because Kotlin never gets updated, only Java changes and gets new features added to it.

I appreciate sarcasm, but it comes across as unnecessary and a bit rude.

Although you do make some good points - especially after trying Java / Kotlin converters - which either:
- don't work well at all, or
- outputs some direct representation of Java bytecode _(which is arguably even worse)_. 

So I may just convert a file here or there if I contribute. Java & Kotlin are interoperable.

**Comment by Aashishkebab** [comment]
> I appreciate sarcasm, but it comes across as unnecessary and a bit rude.

This was after this snobbish comment:

> Honestly the biggest thing holding me back from looking at the code I've just described in Issue #6

If you don't want to "look at the code", you don't have to; nobody asked you to.

**Comment by cheeseonamonkey** [comment]
I didn't think it was snobbish, but I have edited it to communicate more clearly my sentiment. Apologies.
